---
---

<link rel="stylesheet" href="styles.css" type="text/css">

<!-- ## master thesis -->

<!-- I am writing my thesis on the digitization and reconstruction of Kaplan Meier survival curves, involving a Hough transform and the sequential re-estimation of numbers at risk given the detected deaths and censoring events.  -->

# While in Amsterdam

See [main page](./index.html) of this website and [Google Scholar](https://scholar.google.com/citations?user=28Ouga0AAAAJ&hl=en&oi=sra).

---

# Before Amsterdam

## Robust Association Measures

Group [project](./files/Robust.pdf) at KU Leuven testing different robust association measures between two multivariate variables.

## Generalized Linear Mixed Models

Group [project](./files/GLM_Project.pdf) at KU Leuven on Poisson regression models and cubic penalized splines.

## Transgovernmental Networks

Assisting research in a quantitative [study](http://wp.peio.me/wp-content/uploads/2016/12/PEIO10_paper_46.pdf) of democratic legitimacy of transgovernmental networks

## Debt Relief Efficiency

My Bachelor Thesis under the advisement of Dr. Guido Cozzi at the University of St Gallen focuses on the efficiency of IMF and WB debt relief. The first part consisted of estimating the effect of relief on GDP growth measured by a counterfactual estimator, using a control group of similar but non-relieved countries. Then an analysis of Time Series data on the millenium development goals was made, so as to measure the effect of relief on the stated goals of the relief initiatives, again for both control and treatment groups. The paper was published at the university library but is only available to current students and alumni. I made it available [here](./files/Debt_Relief_Efficiency.pdf) though.

## Aumann and Nash

High-school Thesis on Game Theory with a reformulation of the proof of the Nash Equilibrium for my [*Masterarbeit*](./files/TM_BENEDICT_Garbiel.pdf), with the substantial help of my supervisor Prof. Luc Dessauges and a lucky encounter with [Prof. Aumann](https://en.wikipedia.org/wiki/Robert_Aumann).



